name: Build and publish pre-release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.1xx
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish "ADACL CLI/ADACL CLI.csproj" -c Release -o release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ADACL
        path: "/home/runner/work/ADACL/ADACL/release/"
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN }}"
        automatic_release_tag: "devbuild"
        prerelease: true
        title: "Development Build"
        files: |
          "/home/runner/work/ADACL/ADACL/release/*"
